version: "3.7"
services:
  mysql:
    container_name: mysql-test
    image: mysql:5.7
    volumes:
      - ./volume/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: 1234
